## Docker compose file created by: Joan Francesc Pedro

version: '3'

services:
  gitea-db:
    image: postgres:alpine
    container_name: gitea-db
    restart: always
    env_file:
      - ./postgres/variables.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dev-net

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    env_file:
      - ./gitea/variables.env
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - dev-net
    ports:
      - '3000:3000'
      - '2222:22'
    depends_on:
      - gitea-db

  #jenkins:
  #  image: joanfrancescpedro/jenkins
  #  container_name: jenkins
  #  restart: always
  #  build:
  #    context: ./Jenkins
  #  networks:
  #    - dev-net
  #  ports:
  #    - '8080:8080'
  #  depends_on:
  #    - gitea


volumes:
  db-data:
    name: db-data
    driver: local
  gitea-data:
    name: gitea-data
    driver: local

networks:
  dev-net:
    driver: bridge
    name: dev-net 
    external: false