## Docker compose file created by: Joan Francesc Pedro

version: '3'

services:
  gitea-db:
    image: postgres:latest
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_USER=giteadb
      - POSTGRES_PASSWORD=giteadb
      - POSTGRES_DB=gitea
    networks:
      - dev-net
    volumes:
      - db-data:/var/lib/postgresql/data

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=giteadb
      - GITEA__database__PASSWD=giteadb
    restart: always
    networks:
      - dev-net
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
      - '2222:22'
    depends_on:
      - gitea-db

  #jenkins:
  #  image: joanfrancescpedro/jenkins
  #  container_name: jenkins
  #  restart: always
  #  build:
  #    context: ./Jenkins
  #  networks:
  #    - dev-net
  #  ports:
  #    - '8080:8080'
  #  depends_on:
  #    - gitea


volumes:
  db-data:
    name: db-data
    driver: local
  gitea-data:
    name: gitea-data
    driver: local

networks:
  dev-net:
    driver: bridge
    name: dev-net 
    external: false