## Docker compose file created by: Joan Francesc Pedro

version: '3'

services:
  gitea-db:
    image: postgres:alpine
    container_name: gitea-db
    restart: always
    env_file:
      - ./postgres/variables-postgres.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - DevOps-net

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    env_file:
      - ./gitea/variables-gitea.env
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - DevOps-net
    ports:
      - '3000:3000'
      - '2222:22'
    depends_on:
      - gitea-db

  #jenkins:
  #  image: joanfrancescpedro/jenkins
  #  container_name: jenkins
  #  restart: always
  #  build:
  #    context: ./Jenkins
  #  networks:
  #    - DevOps-net
  #  ports:
  #    - '8080:8080'
  #  depends_on:
  #    - gitea

  jenkins:
    image: jenkins/jenkins:alpine
    container_name: jenkins
    restart: always
    networks:
      - DevOps-net
    ports:
      - '8080:8080'
    depends_on:
      - gitea

volumes:
  db-data:
    name: db-data
    driver: local
  gitea-data:
    name: gitea-data
    driver: local

networks:
  DevOps-net:
    driver: bridge
    name: DevOps-net 
    external: false
